### ISSUE TITLE
how to obtain the h36m_mosh_train.npz

### ISSUE THREAD

**Issue by sunjc0306** [HongwenZhang/DaNet-3DHumanReconstruction#12]
Hi!
I would like to retrain this code with the human3.6 dataset. However, I meet an error which h36m_mosh_train.npz can not be found.
 Where can I get this file?
thanks!

**Comment by HongwenZhang** [comment]
Hi, we used the moshed labels shared in [HMR](https://github.com/akanazawa/hmr/blob/master/doc/train.md#download-datasets). Unfortunately, the moshed labels can not be redistributed publicly due to the license issue. However, [this repo](https://github.com/mks0601/3DMPPE_ROOTNET_RELEASE) may still help you get the data and labels.
